name: xeus-kernel
channels:
  - https://prefix.dev/emscripten-forge-dev
  - https://prefix.dev/conda-forge
dependencies:
  - xeus-python
  - numpy
  - pandas
  - pip:
    - jupytergis-lab
    - jupytercad-lab
